Host:  "localhost:8938"
PD:    "localhost:2379"
RaftGroup:
  - "1" :
      RaftID:  "1"
      From:    "a"
      To:      "i"
      Address:
        - "localhost:12381"
        - "localhost:22383"
        - "localhost:42380"
  - "2" :
      RaftID:  "2"
      From:    "j"
      To:      "r"
      Address:
        - "localhost:22383"
        - "localhost:32380"
        - "localhost:42380"
  - "3" :
      RaftID:  "3"
      From:    "s"
      To:      "z"
      Address:
        - "localhost:12381"
        - "localhost:22383"
        - "localhost:32380"


