Node:
  - "1" : 
      Host   : ":12381"
      DataDir: "mtikv1"
      RaftID : "1,1"
      RGroup : "1,3"
      Peers  : "1,3"
  - "2" :
      Host   : ":22383"
      DataDir: "mtikv2"
      RaftID : "2,1,2"
      RGroup : "1,2,3"
      Peers  : "1,2,3"
  - "3" :
      Host   : ":32380"
      DataDir: "mtikv3"
      RaftID : "2,3"
      RGroup : "2,3"
      Peers  : "2,3"
  - "4" :
      Host   : ":42380"
      DataDir: "mtikv4"
      RaftID : "3,3"
      RGroup : "1,2"
      Peers  : "1,2"
Network:
  - "1": "http://127.0.0.1:12389,http://127.0.0.1:22579,http://127.0.0.1:32393"
  - "2": "http://127.0.0.1:14379,http://127.0.0.1:24394,http://127.0.0.1:34379"
  - "3": "http://127.0.0.1:13379,http://127.0.0.1:23579,http://127.0.0.1:33579"

